#define SYS_fork 1
#define SYS_exit 2
#define SYS_wait 3
#define SYS_pipe 4
#define SYS_write 5
#define SYS_read 6
#define SYS_close 7
#define SYS_kill 9
#define SYS_exec 10
#define SYS_open 11
#define SYS_mknod 12
#define SYS_unlink 13
#define SYS_fstat 14
#define SYS_link 15
#define SYS_mkdir 16
#define SYS_chdir 17
#define SYS_dup 18
#define SYS_getpid 19
#define SYS_sbrk 20

