// System call numbers
#define SYS_fork    1
#define SYS_exit    2
#define SYS_wait    3
#define SYS_pipe    4
#define SYS_write   5
#define SYS_read    6
#define SYS_close   7
#define SYS_kill    8
#define SYS_exec    9
#define SYS_openat 10
#define SYS_mknod  11
#define SYS_unlink 12
#define SYS_fstat  13
#define SYS_link   14
#define SYS_mkdirat 15
#define SYS_chdir  16
#define SYS_dup    17
#define SYS_getpid 18
#define SYS_sbrk   19
#define SYS_sleep  20
#define SYS_uptime 21
#define SYS_map    22
#define SYS_unmap  23
#define SYS_halt   24
#define SYS_socket 25
#define SYS_bind   26
#define SYS_listen 27
#define SYS_accept 28
#define SYS_pread  29
#define SYS_async  30
#define SYS_script 31
#define SYS_setfs  32
#define SYS_wqwait 33
#define SYS_setaffinity 34
#define SYS_ncount 35   /* total number of system calls */
